server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: data-simulator
  datasource:
    url: jdbc:postgresql://${POSTGIS_HOST:localhost}:${POSTGIS_PORT:5432}/${POSTGIS_DB:telemetry_connector_db}
    username: ${POSTGIS_USER:postgres}
    password: ${POSTGIS_PASSWORD}
    hikari:
      read-only: true
  kafka:
    bootstrap-servers: ${INTERNAL_KAFKA_SERVERS:localhost:9092}
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 100
        generate_statistics: false
    defer-datasource-initialization: false



logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    com.siemens.spfts: ${APP_LOG_LEVEL:DEBUG}


